services:
  jupyter:
    build: .
    container_name: pry_web_desk_jupyter
    env_file:
      - .env
    volumes:
      - ${JUPYTER_HOME}:/app
    ports:
      - "8888:8888"
    networks:
      - grh_network

networks:
  grh_network:
    external: true
